Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "file", source: "default", destination: "/home/vagrant" 
  config.vm.provision "shell", path: "puppet-install.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
  end
end
