Vagrant.configure("2") do |config|
  config.vm.box = "puppetlabs/ubuntu-16.04-32-puppet"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "public_network"
  config.vm.provision "file", source: "default", destination: "/home/vagrant" 
  config.vm.provision "shell", path: "nginx.sh"
end
